version: '3'
services:
  app:
    image: springboot_weather_analyzer:latest
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/weather_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  db:
    image: mysql:latest
    ports:
      - "3308:3307"
    environment:
      MYSQL_DATABASE: weather_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin