version: '3.1'

services:

  mysql:
    image: 'mysql:latest'
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=weather_db
    volumes:
      - ./mysql-data:/var/lib/mysql

  weather_app:
    image: 'springboot_weather_analyzer-image'
    build:
      context: .
    container_name: weather_app
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/weather_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - '8082:8082'

